name: Build, Push, and Deploy REST API

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

env:
  # Define the image name using GHCR convention
  IMAGE_NAME: rest-api-layer
  REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Needs to read secrets for VPS deployment
    permissions:
      contents: read
      packages: write 
      
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      # --- CI: Build and Push to GHCR ---
      
      - name: 🔑 Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔨 Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest, ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          file: ./Dockerfile
      
      # --- CD: Deploy to VPS via SSH ---
      
      - name: 📤 Transfer deployment script to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deployment/deploy.sh"
          target: "/opt/dapr-deployments/"
          strip_components: 1
      
      - name: ⚙️ Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Define paths on VPS
            APP_DIR="/root/Mqtt"
            DEPLOY_PATH="/opt/dapr-deployments"
            
            # Ensure deployment directory exists
            mkdir -p $DEPLOY_PATH
            
            # Make script executable
            chmod +x $DEPLOY_PATH/deploy.sh
            
            # Login to GHCR on VPS
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            
            # Execute deployment script
            $DEPLOY_PATH/deploy.sh \
              ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
              $APP_DIR