name: Build, Push, and Deploy REST API

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

env:
  # Define the image name using GHCR convention
  IMAGE_NAME: rest-api-layer
  REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Needs to read secrets for VPS deployment
    permissions:
      contents: read
      packages: write 
      
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      # --- CI: Build and Push to GHCR ---
      
      - name: 🔑 Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔨 Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest, ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          file: ./Dockerfile
      
      # --- CD: Deploy to VPS via SSH ---
      
      - name: ⚙️ Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # FIX: Navigate to the workspace on the runner for guaranteed path resolution
            # This makes the subsequent 'cat' command work relative to the repository root.
            cd ${{ github.workspace }}
            
            # Define the application deployment directory
            APP_DIR="/root/Mqtt"
            DEPLOY_PATH="/opt/dapr-deployments"
            
            # Create deployment directories
            mkdir -p $APP_DIR
            mkdir -p $DEPLOY_PATH
            
            # 2. Upload the deployment script to a dedicated path
            # The path is now simple 'deployment/deploy.sh' because we changed directories above
            cat <<EOF > $DEPLOY_PATH/deploy.sh
            $(cat deployment/deploy.sh)
            EOF
            chmod +x $DEPLOY_PATH/deploy.sh
            
            # 3. Execute the deployment script on a single line for robust parsing
            /opt/dapr-deployments/deploy.sh \
              ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
              $APP_DIR
